FROM python:3.10

ENV CONTROLLER http://controller:8002

WORKDIR /app

COPY ./Dashboard_with_pages .

RUN pip install -e .
RUN pip install uvicorn

CMD [ "uvicorn",  "Dashboard_with_pages.app:app","--host","0.0.0.0","--port","8050" ]
