FROM python:3.10

ENV CONTROLLER http://controller:8002
ENV SERVER_URL http://keycloak:8080/

WORKDIR /app

COPY ./Dashboard_with_pages .

RUN pip install -e .
RUN pip install gunicorn
RUN pip install python-keycloak

CMD gunicorn --bind 0.0.0.0:8050 app:server
